FROM node:latest
WORKDIR usr/src/app

COPY ./package*.json /usr/src/app/

RUN npm install

copy . /usr/src/app/

RUN apt update && \
    apt install -y wget netcat && \
    wget -q -O /usr/bin/wait-for https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for && \
    chmod +x /usr/bin/wait-for

EXPOSE 3000